
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 05 11:20:57 CEST 2015
//----------------------------------------------------

package compilation.modele.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int priveeVar = 25;
  public static final int EGAL = 7;
  public static final int csteEntiere = 20;
  public static final int PLUS = 4;
  public static final int ecrire = 27;
  public static final int INFERIEUR = 11;
  public static final int nouveau = 31;
  public static final int booleen = 30;
  public static final int csteChaine = 28;
  public static final int SUPERIEUR = 12;
  public static final int DIFFERENT = 8;
  public static final int debut = 23;
  public static final int VIRGULE = 16;
  public static final int MOINS = 5;
  public static final int FAUX = 10;
  public static final int POINTVIRGULE = 14;
  public static final int PARFER = 3;
  public static final int entier = 29;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int error = 1;
  public static final int UMOINS = 13;
  public static final int VRAI = 9;
  public static final int classe = 22;
  public static final int PAROUV = 2;
  public static final int CROCHO = 17;
  public static final int lire = 26;
  public static final int publicVar = 24;
  public static final int FIN = 15;
  public static final int idf = 21;
  public static final int retourne = 19;
  public static final int CROCHF = 18;
}

